namespace CodeIcf.AssetManagement.AdressableManagement
{
    /// <summary>
    /// AdressablesAssetの種類
    /// </summary>
    /// <remarks>各値の表示名がAdressableのグループ名になります</remarks>
    public enum AddressableCategory : int
    {
        Menu = 0,
        Title,
        StageSelect,
        CharacterSelect,
        NewCharacterPerformance,
        ButtonGuide,
        LoadingView,
        Stage_Surface_Main,
        Actor,
        GameScene,
        StageIconThumbnail,
        StageUnlockPerformanceData,
        StageSelect_BgParticle,
        MessageWindow,
        LanguageResources_EN,
        LanguageResources_JP,
        AudioManagement,
        BGM,
        Jingle,
        SE_UI,
        StageData,
        DuplicationResources_NameEdit,
        DuplicationResources_Knife,
        DuplicationResources_Textutes,
        DuplicationResources_Materials,
        InputSystem,
        DuplicationResources_Font,
        DuplicationResources_Models,
        DuplicationResources_Motions,
        DuplicationResources_Archanor,
        DuplicationResources_EffectExamples,
        DuplicationResources_PhysicsMaterials,
        DuplicationResources_Obi,
        DuplicationResources_Other,
        DuplicationResources_StageSelect,
        Vibration,
        Stage_Surface_Branch,
        Stage_BackgroundData,
        DuplicationResources_Stage_Text_EN,
        DuplicationResources_Actor_Emote,
        NewCharacterPerformance_en,
        NewCharacterPerformance_jp,
        EventScene,
        DuplicationResources_Models_NormalCube,
        DuplicationResources_UniqueKey,
        DuplicationResources_PostProccessing,
        HowTo_Chara,
        Stage_Reverse_Main,
        Stage_Reverse_Branch,
        ExtraStageGroupData,
        ExtraStageIcon_Thumbnail,
        ExtraStage_Banner,
        ExtraStageData,
        SE_Chara,
        SE_Stage,
        CharaSkin,
        CharaSkinCatalog,
        CharaSkinThumbnail,
        CharaSkinBackTextImage,
        DuplicationResources_Photon,
        DuplicationResources_Prefab,
        StageIconThumbnail_Exception,
        Achievement,
        Stage_Extra,
    }
}
